/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse */
        get: operations["browse_api_browse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Businesses */
        get: operations["businesses_api_businesses_get"];
        put?: never;
        /** Create Business */
        post: operations["create_business_api_businesses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cities */
        get: operations["cities_api_cities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast */
        get: operations["forecast_api_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/industries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Industry List */
        get: operations["industry_list_api_industries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/bank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Bank */
        post: operations["link_bank_api_me_bank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/city": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set City */
        put: operations["set_city_api_me_city_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Topics */
        put: operations["set_topics_api_me_topics_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ops */
        get: operations["ops_api_ops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/policies/{policy_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ops Resolve */
        post: operations["ops_resolve_api_ops_policies__policy_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ops Settle */
        post: operations["ops_settle_api_ops_settle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/perils": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perils */
        get: operations["perils_api_perils_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policies */
        get: operations["policies_api_policies_get"];
        put?: never;
        /** Bind */
        post: operations["bind_api_policies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policy */
        get: operations["policy_api_policies__policy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quote */
        post: operations["quote_api_quotes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Session */
        post: operations["start_session_api_session_post"];
        /** End Session */
        delete: operations["end_session_api_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topic List */
        get: operations["topic_list_api_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weather */
        get: operations["weather_api_weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BankLink */
        BankLink: {
            /** Account Mask */
            account_mask?: string | null;
            /** Balance Cents */
            balance_cents?: number | null;
            /** Error */
            error?: string | null;
            /** Linked */
            linked: boolean;
        };
        /** BindRequest */
        BindRequest: {
            /**
             * All Or Nothing
             * @default false
             */
            all_or_nothing: boolean;
            /** Quote Id */
            quote_id: string;
        };
        /** BrowseGroup */
        BrowseGroup: {
            /** Id */
            id: string;
            /** Options */
            options: components["schemas"]["BrowseOption"][];
            /** Settles On */
            settles_on: string;
            /** Title */
            title: string;
            /** Warning */
            warning?: string | null;
        };
        /** BrowseOption */
        BrowseOption: {
            /** Chance */
            chance?: number | null;
            /** Closes At */
            closes_at: string;
            /** Label */
            label: string;
            /** Ticker */
            ticker: string;
        };
        /** BrowseResult */
        BrowseResult: {
            /** Groups */
            groups: components["schemas"]["BrowseGroup"][];
            /** Message */
            message?: string | null;
            /**
             * Topic
             * @enum {string}
             */
            topic: "weather" | "fuel" | "rates" | "prices" | "tariffs" | "sports" | "jobs" | "other";
        };
        /** Business */
        Business: {
            /** Bad Day Dollars */
            bad_day_dollars: number;
            bank: components["schemas"]["BankLink"];
            city?: components["schemas"]["City"] | null;
            /** Created At */
            created_at: string;
            /** Description */
            description: string;
            /** Id */
            id: number;
            /** Industry */
            industry: string;
            /** Name */
            name: string;
            /** Topics */
            topics: ("weather" | "fuel" | "rates" | "prices" | "tariffs" | "sports" | "jobs" | "other")[];
        };
        /** BusinessListItem */
        BusinessListItem: {
            city?: components["schemas"]["City"] | null;
            /** Id */
            id: number;
            /** Industry */
            industry: string;
            /** Name */
            name: string;
        };
        /** Choice */
        Choice: {
            /** Chance */
            chance?: number | null;
            /** Closes At */
            closes_at: string;
            /** Label */
            label: string;
            /** Ticker */
            ticker: string;
        };
        /** City */
        City: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** State */
            state: string;
        };
        /** CityUpdate */
        CityUpdate: {
            /** City Id */
            city_id: string;
        };
        /** CoverageDay */
        CoverageDay: {
            /** Date */
            date: string;
            /** Label */
            label: string;
            /** Triggers */
            triggers: components["schemas"]["TriggerOption"][];
        };
        /** CreateBusiness */
        CreateBusiness: {
            /** City Id */
            city_id?: string | null;
            /** Industry */
            industry: string;
            /** Name */
            name: string;
        };
        /** Forecast */
        Forecast: {
            /** Cards */
            cards: components["schemas"]["PlanCard"][];
            /** Note */
            note?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndustryInfo */
        IndustryInfo: {
            /** Name */
            name: string;
        };
        /** LegRequest */
        LegRequest: {
            /**
             * Side
             * @default yes
             * @enum {string}
             */
            side: "yes" | "no";
            /** Ticker */
            ticker: string;
        };
        /** MoneyMovement */
        MoneyMovement: {
            /** Amount Cents */
            amount_cents: number;
            /** Created At */
            created_at: string;
            /** External Id */
            external_id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "premium" | "refund" | "payout";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "done" | "failed";
        };
        /** OpsOverview */
        OpsOverview: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Data Source */
            data_source: string;
            /** Hedge Mode */
            hedge_mode: string;
            /** Policies */
            policies: components["schemas"]["OpsPolicy"][];
            /** Reserve Balance Cents */
            reserve_balance_cents?: number | null;
            /** Reserve Error */
            reserve_error?: string | null;
            worker: components["schemas"]["WorkerStatus"];
        };
        /** OpsPolicy */
        OpsPolicy: {
            /** Business Name */
            business_name: string;
            /** Closes At */
            closes_at: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: number;
            /** Max Payout Cents */
            max_payout_cents: number;
            /** Paid Cents */
            paid_cents: number;
            /** Payout Each Cents */
            payout_each_cents: number;
            /** Premium Cents */
            premium_cents: number;
            /** Simulated */
            simulated: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "ACTIVE" | "AWAITING_RESULT" | "PAID" | "EXPIRED" | "REFUNDED" | "NEEDS_REVIEW";
            /** Title */
            title: string;
            /**
             * Topic
             * @enum {string}
             */
            topic: "weather" | "fuel" | "rates" | "prices" | "tariffs" | "sports" | "jobs" | "other";
        };
        /** Peril */
        Peril: {
            /** Description */
            description: string;
            /**
             * Id
             * @enum {string}
             */
            id: "rain" | "heat" | "cold";
            /** Name */
            name: string;
        };
        /** PlanCard */
        PlanCard: {
            /** Catch */
            catch: string;
            /** Chance */
            chance?: number | null;
            /** Choices */
            choices: components["schemas"]["Choice"][];
            /** Closes At */
            closes_at: string;
            /** Group Title */
            group_title: string;
            /** Id */
            id: string;
            /**
             * Side
             * @enum {string}
             */
            side: "yes" | "no";
            /** Ticker */
            ticker: string;
            /** Title */
            title: string;
            /**
             * Topic
             * @enum {string}
             */
            topic: "weather" | "fuel" | "rates" | "prices" | "tariffs" | "sports" | "jobs" | "other";
            /** Warnings */
            warnings: string[];
            /** Why */
            why: string;
        };
        /** PlanText */
        PlanText: {
            /**
             * Catch
             * @default
             */
            catch: string;
            /** Title */
            title: string;
            /**
             * Topic
             * @enum {string}
             */
            topic: "weather" | "fuel" | "rates" | "prices" | "tariffs" | "sports" | "jobs" | "other";
            /**
             * Why
             * @default
             */
            why: string;
        };
        /** PolicyDetail */
        PolicyDetail: {
            /** Catch */
            catch: string;
            /** Closes At */
            closes_at: string;
            /** Created At */
            created_at: string;
            /** Events */
            events: components["schemas"]["PolicyEvent"][];
            /** Id */
            id: number;
            /** Legs */
            legs: components["schemas"]["PolicyLeg"][];
            /** Max Payout Cents */
            max_payout_cents: number;
            /** Movements */
            movements: components["schemas"]["MoneyMovement"][];
            /** Paid Cents */
            paid_cents: number;
            /** Payout Each Cents */
            payout_each_cents: number;
            /** Premium Cents */
            premium_cents: number;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "ACTIVE" | "AWAITING_RESULT" | "PAID" | "EXPIRED" | "REFUNDED" | "NEEDS_REVIEW";
            /** Terms */
            terms: string;
            /** Title */
            title: string;
            /**
             * Topic
             * @enum {string}
             */
            topic: "weather" | "fuel" | "rates" | "prices" | "tariffs" | "sports" | "jobs" | "other";
            /** Why */
            why: string;
        };
        /** PolicyEvent */
        PolicyEvent: {
            /** Created At */
            created_at: string;
            /** Kind */
            kind: string;
            /** Message */
            message: string;
        };
        /** PolicyLeg */
        PolicyLeg: {
            /** Close Time */
            close_time: string;
            /** Contracts */
            contracts: number;
            /** Cost Cents */
            cost_cents: number;
            /** Fill Price */
            fill_price?: string | null;
            /** Label */
            label: string;
            /** Result */
            result?: string | null;
            /**
             * Side
             * @enum {string}
             */
            side: "yes" | "no";
            /** Simulated */
            simulated: boolean;
            /** Ticker */
            ticker: string;
        };
        /** PolicySummary */
        PolicySummary: {
            /** Closes At */
            closes_at: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: number;
            /** Max Payout Cents */
            max_payout_cents: number;
            /** Paid Cents */
            paid_cents: number;
            /** Payout Each Cents */
            payout_each_cents: number;
            /** Premium Cents */
            premium_cents: number;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "ACTIVE" | "AWAITING_RESULT" | "PAID" | "EXPIRED" | "REFUNDED" | "NEEDS_REVIEW";
            /** Title */
            title: string;
            /**
             * Topic
             * @enum {string}
             */
            topic: "weather" | "fuel" | "rates" | "prices" | "tariffs" | "sports" | "jobs" | "other";
        };
        /** Quote */
        Quote: {
            breakdown: components["schemas"]["QuoteBreakdown"];
            /** Catch */
            catch: string;
            /** Expires At */
            expires_at: string;
            /** Id */
            id: string;
            /** Legs */
            legs: components["schemas"]["QuoteLeg"][];
            /** Max Payout Cents */
            max_payout_cents: number;
            /** Payout Each Cents */
            payout_each_cents: number;
            /** Premium Cents */
            premium_cents: number;
            /** Terms */
            terms: string;
            thin_book: components["schemas"]["ThinBook"];
            /** Title */
            title: string;
            /**
             * Topic
             * @enum {string}
             */
            topic: "weather" | "fuel" | "rates" | "prices" | "tariffs" | "sports" | "jobs" | "other";
            /** Warnings */
            warnings: string[];
            /** Why */
            why: string;
        };
        /** QuoteBreakdown */
        QuoteBreakdown: {
            /** Buffer Cents */
            buffer_cents: number;
            /** Exchange Fee Cents */
            exchange_fee_cents: number;
            /** Hedge Cost Cents */
            hedge_cost_cents: number;
            /** Platform Fee Cents */
            platform_fee_cents: number;
            /** Rounding Cents */
            rounding_cents: number;
        };
        /** QuoteLeg */
        QuoteLeg: {
            /** Avg Price */
            avg_price: string;
            /** Close Time */
            close_time: string;
            /** Contracts */
            contracts: number;
            /** Cost Cents */
            cost_cents: number;
            /** Depth Contracts */
            depth_contracts: number;
            /** Implied Probability */
            implied_probability: number;
            /** Label */
            label: string;
            /**
             * Side
             * @enum {string}
             */
            side: "yes" | "no";
            /** Ticker */
            ticker: string;
        };
        /** QuoteRequest */
        QuoteRequest: {
            /** Legs */
            legs: components["schemas"]["LegRequest"][];
            /** Payout Dollars */
            payout_dollars: number;
            plan?: components["schemas"]["PlanText"] | null;
        };
        /** ResolveRequest */
        ResolveRequest: {
            /**
             * Result
             * @enum {string}
             */
            result: "yes" | "no";
        };
        /** SearchResult */
        SearchResult: {
            /** Cards */
            cards: components["schemas"]["PlanCard"][];
            /** Message */
            message: string;
        };
        /** SessionRequest */
        SessionRequest: {
            /** Business Id */
            business_id: number;
        };
        /** Station */
        Station: {
            /** Basis Note */
            basis_note: string;
            /**
             * Basis Risk
             * @enum {string}
             */
            basis_risk: "low" | "medium" | "high";
            /** Code */
            code: string;
            /** Distance Km */
            distance_km: number;
            /** Name */
            name: string;
        };
        /** ThinBook */
        ThinBook: {
            /** Max Payout Dollars */
            max_payout_dollars: number;
            /** Short */
            short: boolean;
        };
        /** TopicInfo */
        TopicInfo: {
            /** Blurb */
            blurb: string;
            /**
             * Id
             * @enum {string}
             */
            id: "weather" | "fuel" | "rates" | "prices" | "tariffs" | "sports" | "jobs" | "other";
            /** Name */
            name: string;
        };
        /** TopicsUpdate */
        TopicsUpdate: {
            /** Topics */
            topics: ("weather" | "fuel" | "rates" | "prices" | "tariffs" | "sports" | "jobs" | "other")[];
        };
        /** TriggerOption */
        TriggerOption: {
            /** Implied Probability */
            implied_probability?: number | null;
            /** Label */
            label: string;
            /** Ticker */
            ticker: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeatherOptions */
        WeatherOptions: {
            /** Days */
            days: components["schemas"]["CoverageDay"][];
            /** Message */
            message?: string | null;
            peril: components["schemas"]["Peril"];
            station: components["schemas"]["Station"];
        };
        /** WorkerStatus */
        WorkerStatus: {
            /** Enabled */
            enabled: boolean;
            /** Last Result */
            last_result?: string | null;
            /** Last Run At */
            last_run_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    browse_api_browse_get: {
        parameters: {
            query: {
                topic: "weather" | "fuel" | "rates" | "prices" | "tariffs" | "sports" | "jobs" | "other";
            };
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    businesses_api_businesses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessListItem"][];
                };
            };
        };
    };
    create_business_api_businesses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBusiness"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Business"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cities_api_cities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["City"][];
                };
            };
        };
    };
    forecast_api_forecast_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Forecast"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    industry_list_api_industries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustryInfo"][];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Business"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_bank_api_me_bank_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Business"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_city_api_me_city_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Business"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_topics_api_me_topics_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Business"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ops_api_ops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsOverview"];
                };
            };
        };
    };
    ops_resolve_api_ops_policies__policy_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ops_settle_api_ops_settle_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsOverview"];
                };
            };
        };
    };
    perils_api_perils_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Peril"][];
                };
            };
        };
    };
    policies_api_policies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_api_policies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    policy_api_policies__policy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: number;
            };
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_api_quotes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_api_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Business"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_api_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    topic_list_api_topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicInfo"][];
                };
            };
        };
    };
    weather_api_weather_get: {
        parameters: {
            query: {
                peril: "rain" | "heat" | "cold";
            };
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherOptions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
