/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/businesses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Businesses */
        get: operations["businesses_api_businesses_get"];
        put?: never;
        /** Create Business */
        post: operations["create_business_api_businesses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cities */
        get: operations["cities_api_cities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage */
        get: operations["coverage_api_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/bank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Bank */
        post: operations["link_bank_api_me_bank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ops */
        get: operations["ops_api_ops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/policies/{policy_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ops Resolve */
        post: operations["ops_resolve_api_ops_policies__policy_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ops Settle */
        post: operations["ops_settle_api_ops_settle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/perils": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perils */
        get: operations["perils_api_perils_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policies */
        get: operations["policies_api_policies_get"];
        put?: never;
        /** Bind */
        post: operations["bind_api_policies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policy */
        get: operations["policy_api_policies__policy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quote */
        post: operations["quote_api_quotes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Session */
        post: operations["start_session_api_session_post"];
        /** End Session */
        delete: operations["end_session_api_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityItem */
        ActivityItem: {
            /** Created At */
            created_at: string;
            /** Message */
            message: string;
            /** Policy Id */
            policy_id: number;
        };
        /** BankLink */
        BankLink: {
            /** Account Mask */
            account_mask?: string | null;
            /** Balance Cents */
            balance_cents?: number | null;
            /** Error */
            error?: string | null;
            /** Linked */
            linked: boolean;
        };
        /** BindRequest */
        BindRequest: {
            /**
             * All Or Nothing
             * @default false
             */
            all_or_nothing: boolean;
            /** Quote Id */
            quote_id: string;
        };
        /** Business */
        Business: {
            bank: components["schemas"]["BankLink"];
            city: components["schemas"]["City"];
            /** Created At */
            created_at: string;
            /** Id */
            id: number;
            /** Industry */
            industry: string;
            /** Name */
            name: string;
        };
        /** BusinessListItem */
        BusinessListItem: {
            city: components["schemas"]["City"];
            /** Id */
            id: number;
            /** Industry */
            industry: string;
            /** Name */
            name: string;
        };
        /** City */
        City: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** State */
            state: string;
        };
        /** CoverageDay */
        CoverageDay: {
            /** Date */
            date: string;
            /** Label */
            label: string;
            /** Triggers */
            triggers: components["schemas"]["TriggerOption"][];
        };
        /** CoverageOptions */
        CoverageOptions: {
            /** Days */
            days: components["schemas"]["CoverageDay"][];
            /** Message */
            message?: string | null;
            peril: components["schemas"]["Peril"];
            station?: components["schemas"]["Station"] | null;
        };
        /** CreateBusiness */
        CreateBusiness: {
            /** City Id */
            city_id: string;
            /** Industry */
            industry: string;
            /** Name */
            name: string;
        };
        /** Dashboard */
        Dashboard: {
            /** Active Coverage Cents */
            active_coverage_cents: number;
            /** Activity */
            activity: components["schemas"]["ActivityItem"][];
            business: components["schemas"]["Business"];
            /** Payouts Received Cents */
            payouts_received_cents: number;
            /** Policies */
            policies: components["schemas"]["PolicySummary"][];
            /** Premiums Paid Cents */
            premiums_paid_cents: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MoneyMovement */
        MoneyMovement: {
            /** Amount Cents */
            amount_cents: number;
            /** Created At */
            created_at: string;
            /** External Id */
            external_id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "premium" | "refund" | "payout";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "done" | "failed";
        };
        /** OpsOverview */
        OpsOverview: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Data Source */
            data_source: string;
            /** Hedge Mode */
            hedge_mode: string;
            /** Policies */
            policies: components["schemas"]["OpsPolicy"][];
            /** Reserve Balance Cents */
            reserve_balance_cents?: number | null;
            /** Reserve Error */
            reserve_error?: string | null;
            worker: components["schemas"]["WorkerStatus"];
        };
        /** OpsPolicy */
        OpsPolicy: {
            /**
             * Basis Risk
             * @enum {string}
             */
            basis_risk: "low" | "medium" | "high";
            /** Business Name */
            business_name: string;
            /** Coverage Dates */
            coverage_dates: string[];
            /** Created At */
            created_at: string;
            /** Id */
            id: number;
            /** Max Payout Cents */
            max_payout_cents: number;
            /** Paid Cents */
            paid_cents: number;
            /** Payout Per Day Cents */
            payout_per_day_cents: number;
            /**
             * Peril
             * @enum {string}
             */
            peril: "rain" | "heat" | "cold";
            /** Premium Cents */
            premium_cents: number;
            /** Simulated */
            simulated: boolean;
            /** Station Name */
            station_name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "ACTIVE" | "AWAITING_RESULT" | "PAID" | "EXPIRED" | "REFUNDED" | "NEEDS_REVIEW";
            /** Title */
            title: string;
        };
        /** Peril */
        Peril: {
            /** Description */
            description: string;
            /**
             * Id
             * @enum {string}
             */
            id: "rain" | "heat" | "cold";
            /** Name */
            name: string;
        };
        /** PolicyDetail */
        PolicyDetail: {
            /**
             * Basis Risk
             * @enum {string}
             */
            basis_risk: "low" | "medium" | "high";
            /** Coverage Dates */
            coverage_dates: string[];
            /** Created At */
            created_at: string;
            /** Events */
            events: components["schemas"]["PolicyEvent"][];
            /** Id */
            id: number;
            /** Legs */
            legs: components["schemas"]["PolicyLeg"][];
            /** Max Payout Cents */
            max_payout_cents: number;
            /** Movements */
            movements: components["schemas"]["MoneyMovement"][];
            /** Paid Cents */
            paid_cents: number;
            /** Payout Per Day Cents */
            payout_per_day_cents: number;
            /**
             * Peril
             * @enum {string}
             */
            peril: "rain" | "heat" | "cold";
            /** Premium Cents */
            premium_cents: number;
            /** Station Name */
            station_name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "ACTIVE" | "AWAITING_RESULT" | "PAID" | "EXPIRED" | "REFUNDED" | "NEEDS_REVIEW";
            /** Terms */
            terms: string;
            /** Title */
            title: string;
        };
        /** PolicyEvent */
        PolicyEvent: {
            /** Created At */
            created_at: string;
            /** Kind */
            kind: string;
            /** Message */
            message: string;
        };
        /** PolicyLeg */
        PolicyLeg: {
            /** Close Time */
            close_time: string;
            /** Contracts */
            contracts: number;
            /** Cost Cents */
            cost_cents: number;
            /** Date */
            date: string;
            /** Fill Price */
            fill_price?: string | null;
            /** Label */
            label: string;
            /** Result */
            result?: string | null;
            /** Simulated */
            simulated: boolean;
            /** Ticker */
            ticker: string;
        };
        /** PolicySummary */
        PolicySummary: {
            /**
             * Basis Risk
             * @enum {string}
             */
            basis_risk: "low" | "medium" | "high";
            /** Coverage Dates */
            coverage_dates: string[];
            /** Created At */
            created_at: string;
            /** Id */
            id: number;
            /** Max Payout Cents */
            max_payout_cents: number;
            /** Paid Cents */
            paid_cents: number;
            /** Payout Per Day Cents */
            payout_per_day_cents: number;
            /**
             * Peril
             * @enum {string}
             */
            peril: "rain" | "heat" | "cold";
            /** Premium Cents */
            premium_cents: number;
            /** Station Name */
            station_name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "ACTIVE" | "AWAITING_RESULT" | "PAID" | "EXPIRED" | "REFUNDED" | "NEEDS_REVIEW";
            /** Title */
            title: string;
        };
        /** Quote */
        Quote: {
            breakdown: components["schemas"]["QuoteBreakdown"];
            /** Expires At */
            expires_at: string;
            /** Id */
            id: string;
            /** Legs */
            legs: components["schemas"]["QuoteLeg"][];
            /** Max Payout Cents */
            max_payout_cents: number;
            /** Payout Per Day Cents */
            payout_per_day_cents: number;
            peril: components["schemas"]["Peril"];
            /** Premium Cents */
            premium_cents: number;
            station: components["schemas"]["Station"];
            /** Terms */
            terms: string;
            thin_book: components["schemas"]["ThinBook"];
            /** Warnings */
            warnings: string[];
        };
        /** QuoteBreakdown */
        QuoteBreakdown: {
            /** Buffer Cents */
            buffer_cents: number;
            /** Exchange Fee Cents */
            exchange_fee_cents: number;
            /** Hedge Cost Cents */
            hedge_cost_cents: number;
            /** Platform Fee Cents */
            platform_fee_cents: number;
            /** Rounding Cents */
            rounding_cents: number;
        };
        /** QuoteLeg */
        QuoteLeg: {
            /** Avg Price */
            avg_price: string;
            /** Contracts */
            contracts: number;
            /** Cost Cents */
            cost_cents: number;
            /** Date */
            date: string;
            /** Depth Contracts */
            depth_contracts: number;
            /** Implied Probability */
            implied_probability: number;
            /** Label */
            label: string;
            /** Ticker */
            ticker: string;
        };
        /** QuoteRequest */
        QuoteRequest: {
            /** Payout Dollars */
            payout_dollars: number;
            /**
             * Peril
             * @enum {string}
             */
            peril: "rain" | "heat" | "cold";
            /** Tickers */
            tickers: string[];
        };
        /** ResolveRequest */
        ResolveRequest: {
            /**
             * Result
             * @enum {string}
             */
            result: "yes" | "no";
        };
        /** SessionRequest */
        SessionRequest: {
            /** Business Id */
            business_id: number;
        };
        /** Station */
        Station: {
            /** Basis Note */
            basis_note: string;
            /**
             * Basis Risk
             * @enum {string}
             */
            basis_risk: "low" | "medium" | "high";
            /** Code */
            code: string;
            /** Distance Km */
            distance_km: number;
            /** Name */
            name: string;
        };
        /** ThinBook */
        ThinBook: {
            /** Max Payout Dollars */
            max_payout_dollars: number;
            /** Short */
            short: boolean;
        };
        /** TriggerOption */
        TriggerOption: {
            /** Implied Probability */
            implied_probability?: number | null;
            /** Label */
            label: string;
            /** Ticker */
            ticker: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkerStatus */
        WorkerStatus: {
            /** Enabled */
            enabled: boolean;
            /** Last Result */
            last_result?: string | null;
            /** Last Run At */
            last_run_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    businesses_api_businesses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessListItem"][];
                };
            };
        };
    };
    create_business_api_businesses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBusiness"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Business"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cities_api_cities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["City"][];
                };
            };
        };
    };
    coverage_api_coverage_get: {
        parameters: {
            query: {
                peril: "rain" | "heat" | "cold";
            };
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageOptions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Business"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_bank_api_me_bank_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Business"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ops_api_ops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsOverview"];
                };
            };
        };
    };
    ops_resolve_api_ops_policies__policy_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ops_settle_api_ops_settle_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsOverview"];
                };
            };
        };
    };
    perils_api_perils_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Peril"][];
                };
            };
        };
    };
    policies_api_policies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_api_policies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    policy_api_policies__policy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: number;
            };
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_api_quotes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_business?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_api_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Business"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_api_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
